---
openapi: 3.0.1
info:
  title: API V1
  version: v1
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  "/api/v1/auth/login":
    post:
      summary: Logs in a user
      tags:
      - Authentication
      parameters: []
      responses:
        '200':
          description: User logged in
        '401':
          description: Invalid credentials
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
  "/api/v2/categories":
    get:
      summary: list categories
      tags:
      - Categories
      security:
      - bearerAuth: []
      responses:
        '200':
          description: successful
    post:
      summary: create category
      tags:
      - Categories
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '201':
          description: created
        '422':
          description: unprocessable entity
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
  "/api/v2/categories/{id}":
    parameters:
    - name: id
      in: path
      description: ID
      required: true
      schema:
        type: string
    get:
      summary: show category
      tags:
      - Categories
      security:
      - bearerAuth: []
      responses:
        '200':
          description: successful
        '404':
          description: not found
        '401':
          description: unauthorized
    patch:
      summary: update category
      tags:
      - Categories
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '200':
          description: successful
        '422':
          description: unprocessable entity
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
    delete:
      summary: delete category
      tags:
      - Categories
      security:
      - bearerAuth: []
      responses:
        '204':
          description: no content
        '404':
          description: not found
        '401':
          description: unauthorized
  "/api/v1/orders":
    post:
      summary: Creates an order
      tags:
      - Orders
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '201':
          description: order created
        '422':
          description: invalid request
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                first_name:
                  type: string
                last_name:
                  type: string
                phone_number:
                  type: string
                email:
                  type: string
                country:
                  type: string
                pincode:
                  type: string
                area:
                  type: string
                city:
                  type: string
                state:
                  type: string
                address:
                  type: string
                total_price:
                  type: number
                address_type:
                  type: string
                payment_status:
                  type: string
                placed_at:
                  type: string
                  format: date-time
                order_items_attributes:
                  type: array
                  items:
                    type: object
                    properties:
                      product_item_id:
                        type: integer
                      quantity:
                        type: integer
                      sub_total:
                        type: number
              required:
              - first_name
              - last_name
              - phone_number
              - email
              - country
              - pincode
              - area
              - city
              - state
              - address
              - total_price
              - address_type
              - payment_status
              - placed_at
              - order_items_attributes
  "/api/v2/categories/{category_id}/subcategories":
    parameters:
    - name: category_id
      in: path
      description: Category ID
      required: true
      schema:
        type: integer
    get:
      summary: list subcategories
      tags:
      - Subcategories
      security:
      - bearerAuth: []
      responses:
        '200':
          description: successful
    post:
      summary: create subcategory
      tags:
      - Subcategories
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '201':
          description: created
        '422':
          description: unprocessable entity
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
  "/api/v2/categories/{category_id}/subcategories/{id}":
    parameters:
    - name: category_id
      in: path
      description: Category ID
      required: true
      schema:
        type: integer
    - name: id
      in: path
      description: ID
      required: true
      schema:
        type: integer
    get:
      summary: show subcategory
      tags:
      - Subcategories
      security:
      - bearerAuth: []
      responses:
        '200':
          description: successful
        '404':
          description: not found
        '401':
          description: unauthorized
    patch:
      summary: update subcategory
      tags:
      - Subcategories
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '200':
          description: successful
        '422':
          description: unprocessable entity
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
    delete:
      summary: delete subcategory
      tags:
      - Subcategories
      security:
      - bearerAuth: []
      responses:
        '204':
          description: no content
        '404':
          description: not found
        '401':
          description: unauthorized
  "/api/v1/users":
    post:
      summary: Creates a user
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: user created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
              - name
              - email
              - password
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
